
/* 
Related docs:
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/
*/

enum TwitchEventId {
    AutomodMessageHold = 'automod.message.hold',
    AutomodMessageUpdate = 'automod.message.update',
    AutomodSettingsUpdate = 'automod.settings.update',
    AutomodTermsUpdate = 'automod.terms.update',
    ChannelUpdate = 'channel.update',
    ChannelFollow = 'channel.follow',
    ChannelAdBreakBegin = 'channel.ad_break.begin',
    ChannelChatClear = 'channel.chat.clear',
    ChannelChatClearUserMessages = 'channel.chat.clear_user_messages',
    ChannelChatMessage = 'channel.chat.message',
    ChannelChatMessageDelete = 'channel.chat.message_delete',
    ChannelChatNotification = 'channel.chat.notification',
    ChannelChatSettingsUpdate = 'channel.chat_settings.update',
    ChannelChatUserMessageHold = 'channel.chat.user_message_hold',
    ChannelChatUserMessageUpdate = 'channel.chat.user_message_update',
    ChannelSubscribe = 'channel.subscribe',
    ChannelSubscriptionEnd = 'channel.subscription.end',
    ChannelSubscriptionGift = 'channel.subscription.gift',
    ChannelSubscriptionMessage = 'channel.subscription.message',
    ChannelCheer = 'channel.cheer',
    ChannelRaid = 'channel.raid',
    ChannelBan = 'channel.ban',
    ChannelUnban = 'channel.unban',
    ChannelUnbanRequestCreate = 'channel.unban_request.create',
    ChannelUnbanRequestResolve = 'channel.unban_request.resolve',
    ChannelModerate = 'channel.moderate',
    ChannelModeratorAdd = 'channel.moderator.add',
    ChannelModeratorRemove = 'channel.moderator.remove',
    ChannelGuestStarSessionBegin = 'channel.guest_star_session.begin',
    ChannelGuestStarSessionEnd = 'channel.guest_star_session.end',
    ChannelGuestStarGuestUpdate = 'channel.guest_star_guest.update',
    ChannelGuestStarSettingsUpdate = 'channel.guest_star_settings.update',
    ChannelChannelPointsAutomaticRewardRedemptionAdd = 'channel.channel_points_automatic_reward_redemption.add',
    ChannelChannelPointsCustomRewardAdd = 'channel.channel_points_custom_reward.add',
    ChannelChannelPointsCustomRewardUpdate = 'channel.channel_points_custom_reward.update',
    ChannelChannelPointsCustomRewardRemove = 'channel.channel_points_custom_reward.remove',
    ChannelChannelPointsCustomRewardRedemptionAdd = 'channel.channel_points_custom_reward_redemption.add',
    ChannelChannelPointsCustomRewardRedemptionUpdate = 'channel.channel_points_custom_reward_redemption.update',
    ChannelPollBegin = 'channel.poll.begin',
    ChannelPollProgress = 'channel.poll.progress',
    ChannelPollEnd = 'channel.poll.end',
    ChannelPredictionBegin = 'channel.prediction.begin',
    ChannelPredictionProgress = 'channel.prediction.progress',
    ChannelPredictionLock = 'channel.prediction.lock',
    ChannelPredictionEnd = 'channel.prediction.end',
    ChannelSuspiciousUserMessage = 'channel.suspicious_user.message',
    ChannelSuspiciousUserUpdate = 'channel.suspicious_user.update',
    ChannelVipAdd = 'channel.vip.add',
    ChannelVipRemove = 'channel.vip.remove',
    ChannelWarningAcknowledge = 'channel.warning.acknowledge',
    ChannelWarningSend = 'channel.warning.send',
    ChannelCharityCampaignDonate = 'channel.charity_campaign.donate',
    ChannelCharityCampaignStart = 'channel.charity_campaign.start',
    ChannelCharityCampaignProgress = 'channel.charity_campaign.progress',
    ChannelCharityCampaignStop = 'channel.charity_campaign.stop',
    ConduitShardDisabled = 'conduit.shard.disabled',
    DropEntitlementGrant = 'drop.entitlement.grant',
    ExtensionBitsTransactionCreate = 'extension.bits_transaction.create',
    ChannelGoalBegin = 'channel.goal.begin',
    ChannelGoalProgress = 'channel.goal.progress',
    ChannelGoalEnd = 'channel.goal.end',
    ChannelHypeTrainBegin = 'channel.hype_train.begin',
    ChannelHypeTrainProgress = 'channel.hype_train.progress',
    ChannelHypeTrainEnd = 'channel.hype_train.end',
    ChannelShieldModeBegin = 'channel.shield_mode.begin',
    ChannelShieldModeEnd = 'channel.shield_mode.end',
    ChannelShoutoutCreate = 'channel.shoutout.create',
    ChannelShoutoutReceive = 'channel.shoutout.receive',
    StreamOnline = 'stream.online',
    StreamOffline = 'stream.offline',
    UserAuthorizationGrant = 'user.authorization.grant',
    UserAuthorizationRevoke = 'user.authorization.revoke',
    UserUpdate = 'user.update',
    UserWhisperMessage = 'user.whisper.message',
}

export default TwitchEventId;