name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
# projects: ["kajahl/4"]
assignees:
  - kajahl
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
        Please provide as much detail as possible so we can help you quickly. 🚀
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue in detail. Include screenshots if possible.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: Describe the expected behavior.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Specify your OS, browser, Node.js version, or any other relevant details.
      placeholder: "e.g., Windows 11, Node.js 18.12.1, Chrome 120"

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant logs. This will be automatically formatted as code.
      render: shell