name: Publish Production Release to npm
on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ""
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 

      - name: Checkout main branch
        run: git checkout main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Get release version from tag
        run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Clean cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build project (TypeScript)
        run: npm run build

      - name: Update package.json version
        run: npm version "${{ env.RELEASE_VERSION }}" --no-git-tag-version

      - name: Commit updated package.json version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Update package.json version to ${{ env.RELEASE_VERSION }}"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to npm
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create pull request from main to develop
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Synchronize develop with production release ${{ env.RELEASE_VERSION }}"
          body: "Automatically create a pull request from main to develop once a new production version is released."
          base: develop
          branch: main
          commit-message: "Synchronize develop with production release ${{ env.RELEASE_VERSION }}"
          labels: |
            auto-pr
